x=read.table(file="clipboard",sep="\t",header=TRUE);x
library(tseries)
library(TTR)
library(forecast)
a=x$amount;a
data=c(a) 
data 
tss=ts(data,frequency=12,start=c(2014,1))
tss 
plot.ts(tss) 
acf(tss) 
pacf(tss)
dec=decompose(tss,"multiplicative");dec 
plot(dec) 
res=dec$random;res
plot(res) 
shapiro.test(res) 
adf.test(tss) 
kpss.test(tss) 
tss1=diff(tss);tss1 
plot(tss1) 
z=ndiffs(tss)
z
Box.test(tss1) 
adf.test(tss1)
kpss.test(tss1)
c=auto.arima(tss);c
forecast(c)